export const products = [
    {
      id: 1,
      name: "MEDIUM BUS",
      negara: "Bahrain",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
      id: 2,
      name: "MEDIUM BUS LONG",
      category: "Harga Mulai",
      price: 20,
      image: "/images/products/logo.png",
      isCart: false,
      description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
    },
    {
      id: 3,
      name: "BIG BUS",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 4,
      name: "ELF LONG",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
    },
    {
      id: 5,
      name: "TOYOTA HIACE",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 6,
      name: "INNOVA REBORN",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 7,
      name: "AVANZA",
      category: "Harga Mulai",
      price: 1200000,
      image: "/images/products/logo.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    }
  ];